# Site settings
title: CS 294 Fairness in Machine Learning
email: 
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fairmlclass.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
